### ISSUE TITLE
Estimator producing non-smooth orientation estimates.

### ISSUE THREAD

**Issue by alexmillane** [ethz-asl/ros_vrpn_client#25]
This is still apparently occurring. Testing requires wrapping the current estimator in a layer such that one can subscribe to raw vicon data.

**Comment by burrimi** [comment]
solved?

**Comment by alexmillane** [comment]
@burrimi The first part is solved; I have written the wrapper which allows to run the estimator on bagfiles. Actually solving the problem with ros_vrpn_client is still outstanding but as of this morning is receiving 100% of my attention. Hopefully I'll solve this this evening or tomorrow.

**Comment by alexmillane** [comment]
Addressed in #29
